#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:8000}"
PROM_URL="${PROM_URL:-http://localhost:9090}"
INQUIRY_FEATURE_ENABLED="${INQUIRY_FEATURE_ENABLED:-true}"
EXPECT_MIGRATION_MATCH="${EXPECT_MIGRATION_MATCH:-true}"
PHASE8_CROSS_DOMAIN_ENABLED="${PHASE8_CROSS_DOMAIN_ENABLED:-true}"
PHASE8_PAIR_PROFILES="${PHASE8_PAIR_PROFILES:-finance_habits_v1,projects_skills_v1,journal_habits_v1,health_habits_v1,projects_calendar_v1,relationships_journal_v1}"
PHASE8_EXPECT_PROFILE_VERSION="${PHASE8_EXPECT_PROFILE_VERSION:-1.0.0}"
PHASE8_EXPECT_STRATEGY_VERSION="${PHASE8_EXPECT_STRATEGY_VERSION:-1.0.0}"
PHASE8_1_PRODUCTIZATION_ENABLED="${PHASE8_1_PRODUCTIZATION_ENABLED:-true}"
PHASE8_1_EXPECT_PRODUCTIZATION_VERSION="${PHASE8_1_EXPECT_PRODUCTIZATION_VERSION:-phase8_1_productization_v1}"
PHASE9_TIMELINE_ENABLED="${PHASE9_TIMELINE_ENABLED:-true}"
PHASE9_FIRST_WAVE_DOMAINS="${PHASE9_FIRST_WAVE_DOMAINS:-finance,habits,projects,skills,calendar}"
PHASE9_APPROVED_PAIR_DOMAINS="${PHASE9_APPROVED_PAIR_DOMAINS:-finance+habits,projects+skills,calendar+projects}"
PHASE9_EXPECTED_PROFILES="${PHASE9_EXPECTED_PROFILES:-finance_timeline_v1,habits_timeline_v1,projects_timeline_v1,skills_timeline_v1,calendar_timeline_v1,finance_habits_timeline_v1,projects_skills_timeline_v1,projects_calendar_timeline_v1}"
PHASE9_EXPECT_PROFILE_VERSION="${PHASE9_EXPECT_PROFILE_VERSION:-1.0.0}"
PHASE9_EXPECT_STRATEGY_VERSION="${PHASE9_EXPECT_STRATEGY_VERSION:-1.0.0}"
PHASE10_HUMANIZATION_ENABLED="${PHASE10_HUMANIZATION_ENABLED:-true}"
PHASE10_EXPECT_HUMANIZATION_VERSION="${PHASE10_EXPECT_HUMANIZATION_VERSION:-phase10_humanization_v1}"
PHASE10_CANARY_PROFILE="${PHASE10_CANARY_PROFILE:-}"
PHASE10_CANARY_MAX_FALLBACK_RATE="${PHASE10_CANARY_MAX_FALLBACK_RATE:-0.20}"
PHASE10_CANARY_MAX_FAILURE_RATE="${PHASE10_CANARY_MAX_FAILURE_RATE:-0.08}"
PHASE10_CANARY_MAX_LATENCY_P95="${PHASE10_CANARY_MAX_LATENCY_P95:-0.25}"
PHASE10_CANARY_MAX_EQUIVALENCE_VIOLATION_COUNT="${PHASE10_CANARY_MAX_EQUIVALENCE_VIOLATION_COUNT:-0}"
PHASE10_CANARY_MAX_REFINE_AFTER_VIEW_RATE="${PHASE10_CANARY_MAX_REFINE_AFTER_VIEW_RATE:-0.70}"

BASE_URL="${BASE_URL}" \
PROM_URL="${PROM_URL}" \
INQUIRY_FEATURE_ENABLED="${INQUIRY_FEATURE_ENABLED}" \
EXPECT_MIGRATION_MATCH="${EXPECT_MIGRATION_MATCH}" \
PHASE8_CROSS_DOMAIN_ENABLED="${PHASE8_CROSS_DOMAIN_ENABLED}" \
PHASE8_PAIR_PROFILES="${PHASE8_PAIR_PROFILES}" \
PHASE8_EXPECT_PROFILE_VERSION="${PHASE8_EXPECT_PROFILE_VERSION}" \
PHASE8_EXPECT_STRATEGY_VERSION="${PHASE8_EXPECT_STRATEGY_VERSION}" \
PHASE8_1_PRODUCTIZATION_ENABLED="${PHASE8_1_PRODUCTIZATION_ENABLED}" \
PHASE8_1_EXPECT_PRODUCTIZATION_VERSION="${PHASE8_1_EXPECT_PRODUCTIZATION_VERSION}" \
PHASE9_TIMELINE_ENABLED="${PHASE9_TIMELINE_ENABLED}" \
PHASE9_FIRST_WAVE_DOMAINS="${PHASE9_FIRST_WAVE_DOMAINS}" \
PHASE9_APPROVED_PAIR_DOMAINS="${PHASE9_APPROVED_PAIR_DOMAINS}" \
PHASE9_EXPECTED_PROFILES="${PHASE9_EXPECTED_PROFILES}" \
PHASE9_EXPECT_PROFILE_VERSION="${PHASE9_EXPECT_PROFILE_VERSION}" \
PHASE9_EXPECT_STRATEGY_VERSION="${PHASE9_EXPECT_STRATEGY_VERSION}" \
PHASE10_HUMANIZATION_ENABLED="${PHASE10_HUMANIZATION_ENABLED}" \
PHASE10_EXPECT_HUMANIZATION_VERSION="${PHASE10_EXPECT_HUMANIZATION_VERSION}" \
PHASE10_CANARY_PROFILE="${PHASE10_CANARY_PROFILE}" \
PHASE10_CANARY_MAX_FALLBACK_RATE="${PHASE10_CANARY_MAX_FALLBACK_RATE}" \
PHASE10_CANARY_MAX_FAILURE_RATE="${PHASE10_CANARY_MAX_FAILURE_RATE}" \
PHASE10_CANARY_MAX_LATENCY_P95="${PHASE10_CANARY_MAX_LATENCY_P95}" \
PHASE10_CANARY_MAX_EQUIVALENCE_VIOLATION_COUNT="${PHASE10_CANARY_MAX_EQUIVALENCE_VIOLATION_COUNT}" \
PHASE10_CANARY_MAX_REFINE_AFTER_VIEW_RATE="${PHASE10_CANARY_MAX_REFINE_AFTER_VIEW_RATE}" \
bash scripts/ops/phase6_inquiry_rollout_check.sh
