#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:8000}"
PROM_URL="${PROM_URL:-http://localhost:9090}"
INQUIRY_FEATURE_ENABLED="${INQUIRY_FEATURE_ENABLED:-true}"
EXPECT_MIGRATION_MATCH="${EXPECT_MIGRATION_MATCH:-true}"
PHASE8_CROSS_DOMAIN_ENABLED="${PHASE8_CROSS_DOMAIN_ENABLED:-true}"
PHASE8_PAIR_PROFILES="${PHASE8_PAIR_PROFILES:-finance_habits_v1,projects_skills_v1,journal_habits_v1,health_habits_v1,projects_calendar_v1,relationships_journal_v1}"
PHASE8_EXPECT_PROFILE_VERSION="${PHASE8_EXPECT_PROFILE_VERSION:-1.0.0}"
PHASE8_EXPECT_STRATEGY_VERSION="${PHASE8_EXPECT_STRATEGY_VERSION:-1.0.0}"
PHASE8_1_PRODUCTIZATION_ENABLED="${PHASE8_1_PRODUCTIZATION_ENABLED:-true}"
PHASE8_1_EXPECT_PRODUCTIZATION_VERSION="${PHASE8_1_EXPECT_PRODUCTIZATION_VERSION:-phase8_1_productization_v1}"
PHASE8_1_CANARY_PROFILE="${PHASE8_1_CANARY_PROFILE:-}"
PHASE8_1_CANARY_MIN_DIRECT_ANSWER_RATE="${PHASE8_1_CANARY_MIN_DIRECT_ANSWER_RATE:-0.55}"
PHASE8_1_CANARY_MAX_WEAK_RATE="${PHASE8_1_CANARY_MAX_WEAK_RATE:-0.70}"

BASE_URL="${BASE_URL}" \
PROM_URL="${PROM_URL}" \
INQUIRY_FEATURE_ENABLED="${INQUIRY_FEATURE_ENABLED}" \
EXPECT_MIGRATION_MATCH="${EXPECT_MIGRATION_MATCH}" \
PHASE8_CROSS_DOMAIN_ENABLED="${PHASE8_CROSS_DOMAIN_ENABLED}" \
PHASE8_PAIR_PROFILES="${PHASE8_PAIR_PROFILES}" \
PHASE8_EXPECT_PROFILE_VERSION="${PHASE8_EXPECT_PROFILE_VERSION}" \
PHASE8_EXPECT_STRATEGY_VERSION="${PHASE8_EXPECT_STRATEGY_VERSION}" \
PHASE8_1_PRODUCTIZATION_ENABLED="${PHASE8_1_PRODUCTIZATION_ENABLED}" \
PHASE8_1_EXPECT_PRODUCTIZATION_VERSION="${PHASE8_1_EXPECT_PRODUCTIZATION_VERSION}" \
PHASE8_1_CANARY_PROFILE="${PHASE8_1_CANARY_PROFILE}" \
PHASE8_1_CANARY_MIN_DIRECT_ANSWER_RATE="${PHASE8_1_CANARY_MIN_DIRECT_ANSWER_RATE}" \
PHASE8_1_CANARY_MAX_WEAK_RATE="${PHASE8_1_CANARY_MAX_WEAK_RATE}" \
bash scripts/ops/phase6_inquiry_rollout_check.sh
