"""empty message

Revision ID: c09915f465f7
Revises: 20251219_calendar_oauth_tokens
Create Date: 2025-12-11 02:50:26.492413
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c09915f465f7'
down_revision = '20251219_calendar_oauth_tokens'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry_tag')
    op.drop_table('journal_tag')
    op.alter_column('calendar_event', 'tags',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('calendar_event', 'metadata',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('calendar_event', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('calendar_event', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_calendar_event_start_time'), 'calendar_event', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_event_user_id'), 'calendar_event', ['user_id'], unique=False)
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_event', 'user', ['user_id'], ['id'])
    op.alter_column('calendar_event_interpretation', 'domain',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('calendar_event_interpretation', 'record_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('calendar_event_interpretation', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=False)
    op.alter_column('calendar_event_interpretation', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'inferred'"))
    op.alter_column('calendar_event_interpretation', 'classification_data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('calendar_event_interpretation', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('calendar_event_interpretation', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_calendar_event_interpretation_calendar_event_id'), 'calendar_event_interpretation', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_interpretation_user_id'), 'calendar_event_interpretation', ['user_id'], unique=False)
    op.drop_constraint(None, 'calendar_event_interpretation', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_event_interpretation', 'user', ['user_id'], ['id'])
    op.alter_column('calendar_oauth_token', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('calendar_oauth_token', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_event_record_created_at'), 'event_record', ['created_at'], unique=False)
    op.alter_column('finance_account', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_account', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('ix_finance_account_type', table_name='finance_account')
    op.create_index(op.f('ix_finance_account_account_type'), 'finance_account', ['account_type'], unique=False)
    op.alter_column('finance_account_category', 'slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('finance_account_category', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('finance_account_category', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index('uq_finance_account_category_user_base_slug', table_name='finance_account_category')
    op.create_unique_constraint('uq_finance_account_category_user_base_slug', 'finance_account_category', ['user_id', 'base_type', 'slug'])
    op.create_index(op.f('ix_finance_account_category_user_id'), 'finance_account_category', ['user_id'], unique=False)
    op.create_foreign_key(None, 'finance_account_category', 'user', ['user_id'], ['id'])
    op.drop_index('ix_finance_money_schedule_row_event_date', table_name='finance_money_schedule_row')
    op.alter_column('finance_transaction', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_finance_transaction_user_inference_status', table_name='finance_transaction')
    op.create_index('ix_finance_transaction_calendar_event', 'finance_transaction', ['calendar_event_id'], unique=False)
    op.create_foreign_key(None, 'finance_transaction', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_health_biometric_user_recorded_at', table_name='health_biometric')
    op.drop_column('health_biometric', 'recorded_at')
    op.drop_column('health_biometric', 'metric')
    op.drop_column('health_biometric', 'value')
    op.alter_column('health_nutrition_log', 'meal_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('health_nutrition_log', 'items',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('health_nutrition_log', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_health_nutrition_log_user_inference_status', table_name='health_nutrition_log')
    op.drop_index('ix_health_nutrition_log_user_logged_at', table_name='health_nutrition_log')
    op.create_index('ix_health_nutrition_log_calendar_event', 'health_nutrition_log', ['calendar_event_id'], unique=False)
    op.create_foreign_key(None, 'health_nutrition_log', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.drop_column('health_nutrition_log', 'fat')
    op.drop_column('health_nutrition_log', 'protein')
    op.drop_column('health_nutrition_log', 'logged_at')
    op.drop_column('health_nutrition_log', 'carbs')
    op.drop_column('health_nutrition_log', 'calories')
    op.drop_column('health_nutrition_log', 'meal')
    op.alter_column('health_workout', 'workout_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('health_workout', 'intensity',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('health_workout', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_health_workout_user_inference_status', table_name='health_workout')
    op.drop_index('ix_health_workout_user_performed_at', table_name='health_workout')
    op.create_index('ix_health_workout_calendar_event', 'health_workout', ['calendar_event_id'], unique=False)
    op.create_foreign_key(None, 'health_workout', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.drop_column('health_workout', 'activity')
    op.drop_column('health_workout', 'performed_at')
    op.drop_column('health_workout', 'calories')
    op.alter_column('journal_entry', 'mood',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_journal_entry_user_mood', table_name='journal_entry')
    op.create_index('ix_journal_entry_user_mood', 'journal_entry', ['user_id', 'mood'], unique=False)
    op.drop_column('journal_entry', 'mood_int')
    op.drop_column('journal_entry', 'content')
    op.drop_index('ix_password_reset_token_user_id', table_name='password_reset_token')
    op.drop_index('ix_platform_outbox_available_at', table_name='platform_outbox')
    op.drop_index('ix_platform_outbox_status', table_name='platform_outbox')
    op.alter_column('project', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('ix_project_user_created_at', table_name='project')
    op.alter_column('project_task', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_task', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_project_task_user_id'), 'project_task', ['user_id'], unique=False)
    op.drop_constraint(None, 'project_task', type_='foreignkey')
    op.create_foreign_key(None, 'project_task', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_task_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_task_log', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('project_task_log', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_project_task_log_user_inference_status', table_name='project_task_log')
    op.create_index('ix_project_task_log_calendar_event', 'project_task_log', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_project_task_log_user_id'), 'project_task_log', ['user_id'], unique=False)
    op.drop_constraint(None, 'project_task_log', type_='foreignkey')
    op.create_foreign_key(None, 'project_task_log', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_task_log', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'project_task_log', 'project_task', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('relationships_interaction', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_relationships_interaction_user_inference_status', table_name='relationships_interaction')
    op.create_index('ix_relationships_interaction_calendar_event', 'relationships_interaction', ['calendar_event_id'], unique=False)
    op.create_foreign_key(None, 'relationships_interaction', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_session_token_user_id', table_name='session_token')
    op.alter_column('skill', 'tags',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('skill', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('skill', 'level')
    op.alter_column('skill_practice_session', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('skill_practice_session', 'confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.drop_index('ix_skill_practice_session_user_inference_status', table_name='skill_practice_session')
    op.create_index(op.f('ix_skill_practice_session_practiced_at'), 'skill_practice_session', ['practiced_at'], unique=False)
    op.create_index(op.f('ix_skill_practice_session_user_id'), 'skill_practice_session', ['user_id'], unique=False)
    op.create_index('ix_skill_session_calendar_event', 'skill_practice_session', ['calendar_event_id'], unique=False)
    op.drop_constraint(None, 'skill_practice_session', type_='foreignkey')
    op.create_foreign_key(None, 'skill_practice_session', 'calendar_event', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'skill_practice_session', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'skill_practice_session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_practice_session', type_='foreignkey')
    op.drop_constraint(None, 'skill_practice_session', type_='foreignkey')
    op.drop_constraint(None, 'skill_practice_session', type_='foreignkey')
    op.create_foreign_key(None, 'skill_practice_session', 'skill', ['skill_id'], ['id'])
    op.drop_index('ix_skill_session_calendar_event', table_name='skill_practice_session')
    op.drop_index(op.f('ix_skill_practice_session_user_id'), table_name='skill_practice_session')
    op.drop_index(op.f('ix_skill_practice_session_practiced_at'), table_name='skill_practice_session')
    op.create_index('ix_skill_practice_session_user_inference_status', 'skill_practice_session', ['user_id', 'inference_status'], unique=False)
    op.alter_column('skill_practice_session', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('skill_practice_session', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('skill', sa.Column('level', sa.VARCHAR(length=32), server_default=sa.text("'beginner'"), nullable=False))
    op.alter_column('skill', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('skill', 'tags',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.create_index('ix_session_token_user_id', 'session_token', ['user_id'], unique=False)
    op.drop_constraint(None, 'relationships_interaction', type_='foreignkey')
    op.drop_index('ix_relationships_interaction_calendar_event', table_name='relationships_interaction')
    op.create_index('ix_relationships_interaction_user_inference_status', 'relationships_interaction', ['user_id', 'inference_status'], unique=False)
    op.alter_column('relationships_interaction', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_constraint(None, 'project_task_log', type_='foreignkey')
    op.drop_constraint(None, 'project_task_log', type_='foreignkey')
    op.drop_constraint(None, 'project_task_log', type_='foreignkey')
    op.create_foreign_key(None, 'project_task_log', 'project_task', ['task_id'], ['id'])
    op.drop_index(op.f('ix_project_task_log_user_id'), table_name='project_task_log')
    op.drop_index('ix_project_task_log_calendar_event', table_name='project_task_log')
    op.create_index('ix_project_task_log_user_inference_status', 'project_task_log', ['user_id', 'inference_status'], unique=False)
    op.alter_column('project_task_log', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('project_task_log', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('project_task_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'project_task', type_='foreignkey')
    op.drop_constraint(None, 'project_task', type_='foreignkey')
    op.create_foreign_key(None, 'project_task', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_project_task_user_id'), table_name='project_task')
    op.alter_column('project_task', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('project_task', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_project_user_created_at', 'project', ['user_id', 'created_at'], unique=False)
    op.alter_column('project', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('ix_platform_outbox_status', 'platform_outbox', ['status'], unique=False)
    op.create_index('ix_platform_outbox_available_at', 'platform_outbox', ['available_at'], unique=False)
    op.create_index('ix_password_reset_token_user_id', 'password_reset_token', ['user_id'], unique=False)
    op.add_column('journal_entry', sa.Column('content', sa.TEXT(), nullable=True))
    op.add_column('journal_entry', sa.Column('mood_int', sa.INTEGER(), nullable=True))
    op.drop_index('ix_journal_entry_user_mood', table_name='journal_entry')
    op.create_index('ix_journal_entry_user_mood', 'journal_entry', ['user_id', 'mood_int'], unique=False)
    op.alter_column('journal_entry', 'mood',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.add_column('health_workout', sa.Column('calories', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('health_workout', sa.Column('performed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('health_workout', sa.Column('activity', sa.VARCHAR(length=128), server_default=sa.text("('')"), nullable=True))
    op.drop_constraint(None, 'health_workout', type_='foreignkey')
    op.drop_index('ix_health_workout_calendar_event', table_name='health_workout')
    op.create_index('ix_health_workout_user_performed_at', 'health_workout', ['user_id', 'performed_at'], unique=False)
    op.create_index('ix_health_workout_user_inference_status', 'health_workout', ['user_id', 'inference_status'], unique=False)
    op.alter_column('health_workout', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('health_workout', 'intensity',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('health_workout', 'workout_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.add_column('health_nutrition_log', sa.Column('meal', sa.VARCHAR(length=128), server_default=sa.text("('')"), nullable=True))
    op.add_column('health_nutrition_log', sa.Column('calories', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=True))
    op.add_column('health_nutrition_log', sa.Column('carbs', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('health_nutrition_log', sa.Column('logged_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('health_nutrition_log', sa.Column('protein', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('health_nutrition_log', sa.Column('fat', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.drop_constraint(None, 'health_nutrition_log', type_='foreignkey')
    op.drop_index('ix_health_nutrition_log_calendar_event', table_name='health_nutrition_log')
    op.create_index('ix_health_nutrition_log_user_logged_at', 'health_nutrition_log', ['user_id', 'logged_at'], unique=False)
    op.create_index('ix_health_nutrition_log_user_inference_status', 'health_nutrition_log', ['user_id', 'inference_status'], unique=False)
    op.alter_column('health_nutrition_log', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('health_nutrition_log', 'items',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('health_nutrition_log', 'meal_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('health_biometric', sa.Column('value', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=True))
    op.add_column('health_biometric', sa.Column('metric', sa.VARCHAR(length=64), server_default=sa.text("('')"), nullable=True))
    op.add_column('health_biometric', sa.Column('recorded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_health_biometric_user_recorded_at', 'health_biometric', ['user_id', 'recorded_at'], unique=False)
    op.drop_constraint(None, 'finance_transaction', type_='foreignkey')
    op.drop_index('ix_finance_transaction_calendar_event', table_name='finance_transaction')
    op.create_index('ix_finance_transaction_user_inference_status', 'finance_transaction', ['user_id', 'inference_status'], unique=False)
    op.alter_column('finance_transaction', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.create_index('ix_finance_money_schedule_row_event_date', 'finance_money_schedule_row', ['event_date'], unique=False)
    op.drop_constraint(None, 'finance_account_category', type_='foreignkey')
    op.drop_index(op.f('ix_finance_account_category_user_id'), table_name='finance_account_category')
    op.drop_constraint('uq_finance_account_category_user_base_slug', 'finance_account_category', type_='unique')
    op.create_index('uq_finance_account_category_user_base_slug', 'finance_account_category', ['user_id', 'base_type', 'slug'], unique=1)
    op.alter_column('finance_account_category', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('finance_account_category', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('finance_account_category', 'slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_finance_account_account_type'), table_name='finance_account')
    op.create_index('ix_finance_account_type', 'finance_account', ['account_type'], unique=False)
    op.alter_column('finance_account', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('finance_account', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_event_record_created_at'), table_name='event_record')
    op.alter_column('calendar_oauth_token', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('calendar_oauth_token', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'calendar_event_interpretation', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_event_interpretation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_calendar_event_interpretation_user_id'), table_name='calendar_event_interpretation')
    op.drop_index(op.f('ix_calendar_event_interpretation_calendar_event_id'), table_name='calendar_event_interpretation')
    op.alter_column('calendar_event_interpretation', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('calendar_event_interpretation', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('calendar_event_interpretation', 'classification_data',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('calendar_event_interpretation', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'inferred'"))
    op.alter_column('calendar_event_interpretation', 'confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('calendar_event_interpretation', 'record_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('calendar_event_interpretation', 'domain',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_event', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_calendar_event_user_id'), table_name='calendar_event')
    op.drop_index(op.f('ix_calendar_event_start_time'), table_name='calendar_event')
    op.alter_column('calendar_event', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('calendar_event', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('calendar_event', 'metadata',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('calendar_event', 'tags',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.create_table('journal_tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('journal_entry_tag',
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['journal_tag.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    # ### end Alembic commands ###
