"""initial_clean_base

Revision ID: 7ff76bbff8bf
Revises: 
Create Date: 2025-12-03 14:32:37.415934

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ff76bbff8bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_schedule_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'CHECKING', 'SAVINGS', name='money_schedule_account_type'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_included_in_closing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'currency', name='uq_money_schedule_account_name_currency')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('tb_group', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eod_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['money_schedule_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_account_snapshot_day')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_date'), 'account_snapshots', ['date'], unique=False)
    op.create_table('account_suggestion_hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_suggestion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('line_id', sa.String(length=64), nullable=True),
    sa.Column('line_type', sa.String(length=10), nullable=True),
    sa.Column('chosen_account', sa.String(length=120), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('model_path', sa.String(length=255), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.Column('predictions', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_suggestion_log_transaction_id'), 'account_suggestion_log', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_account_suggestion_log_user_id'), 'account_suggestion_log', ['user_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('date_parsed', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_reference'), 'journal_entry', ['reference'], unique=False)
    op.create_index(op.f('ix_journal_entry_user_id'), 'journal_entry', ['user_id'], unique=False)
    op.create_table('loan_group',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('counterparty', sa.String(length=160), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_group_user_id'), 'loan_group', ['user_id'], unique=False)
    op.create_table('login_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_schedule_asset_includes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_schedule_asset_includes_account_id'), 'money_schedule_asset_includes', ['account_id'], unique=False)
    op.create_index(op.f('ix_money_schedule_asset_includes_user_id'), 'money_schedule_asset_includes', ['user_id'], unique=False)
    op.create_table('money_schedule_daily_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_money_schedule_balance_user_day')
    )
    op.create_index(op.f('ix_money_schedule_daily_balances_date'), 'money_schedule_daily_balances', ['date'], unique=False)
    op.create_index(op.f('ix_money_schedule_daily_balances_user_id'), 'money_schedule_daily_balances', ['user_id'], unique=False)
    op.create_table('money_schedule_recurring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.String(length=32), nullable=True),
    sa.Column('month_day', sa.Integer(), nullable=True),
    sa.Column('custom_dates', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_schedule_recurring_events_end_date'), 'money_schedule_recurring_events', ['end_date'], unique=False)
    op.create_index(op.f('ix_money_schedule_recurring_events_start_date'), 'money_schedule_recurring_events', ['start_date'], unique=False)
    op.create_index(op.f('ix_money_schedule_recurring_events_user_id'), 'money_schedule_recurring_events', ['user_id'], unique=False)
    op.create_table('money_schedule_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('inflow', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('outflow', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('predicted_closing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_closing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('inflow >= 0', name='ck_money_schedule_inflow_nonneg'),
    sa.CheckConstraint('outflow >= 0', name='ck_money_schedule_outflow_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_money_schedule_user_date')
    )
    op.create_index(op.f('ix_money_schedule_rows_date'), 'money_schedule_rows', ['date'], unique=False)
    op.create_index(op.f('ix_money_schedule_rows_user_id'), 'money_schedule_rows', ['user_id'], unique=False)
    op.create_table('money_schedule_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_start', sa.Date(), nullable=False),
    sa.Column('base_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_schedule_scenarios_user_id'), 'money_schedule_scenarios', ['user_id'], unique=False)
    op.create_table('money_schedule_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', name='money_schedule_tx_status'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['money_schedule_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_schedule_transactions_date'), 'money_schedule_transactions', ['date'], unique=False)
    op.create_table('rate_limit_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_bucket_bucket'), 'rate_limit_bucket', ['bucket'], unique=False)
    op.create_index(op.f('ix_rate_limit_bucket_reset_at'), 'rate_limit_bucket', ['reset_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_bucket_user_id'), 'rate_limit_bucket', ['user_id'], unique=False)
    op.create_table('suggestion_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested', sa.String(length=120), nullable=True),
    sa.Column('actual', sa.String(length=120), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_balance_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_month', sa.Date(), nullable=True),
    sa.Column('initialized_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['account_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_schedule_scenario_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('inflow', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('outflow', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('predicted_closing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_closing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['money_schedule_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'date', name='uq_ms_scenario_day')
    )
    op.create_index(op.f('ix_money_schedule_scenario_rows_date'), 'money_schedule_scenario_rows', ['date'], unique=False)
    op.create_index(op.f('ix_money_schedule_scenario_rows_scenario_id'), 'money_schedule_scenario_rows', ['scenario_id'], unique=False)
    op.create_table('user_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_monthly_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('opening_bd', sa.Float(), nullable=True),
    sa.Column('period_debit', sa.Float(), nullable=True),
    sa.Column('period_credit', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'year', 'month', name='uq_user_acc_ym')
    )
    op.create_index(op.f('ix_account_monthly_balance_account_id'), 'account_monthly_balance', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_monthly_balance_user_id'), 'account_monthly_balance', ['user_id'], unique=False)
    op.create_table('account_opening_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('dc', sa.String(length=1), nullable=False),
    sa.Column('amount_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('amount_tx', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_line_account_id'), 'journal_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_line_journal_id'), 'journal_line', ['journal_id'], unique=False)
    op.create_table('receivable_manual_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('transaction_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_dates', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('date_parsed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivable_manual_entry_account_id'), 'receivable_manual_entry', ['account_id'], unique=False)
    op.create_index(op.f('ix_receivable_manual_entry_user_id'), 'receivable_manual_entry', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('debit_account', sa.String(length=100), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_account', sa.String(length=100), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debit_account_id', sa.Integer(), nullable=True),
    sa.Column('credit_account_id', sa.Integer(), nullable=True),
    sa.Column('date_parsed', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_group_link',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_group_id', sa.String(length=36), nullable=False),
    sa.Column('journal_line_id', sa.Integer(), nullable=False),
    sa.Column('linked_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_line.id'], ),
    sa.ForeignKeyConstraint(['loan_group_id'], ['loan_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_group_id', 'journal_line_id', name='uq_group_line')
    )
    op.create_index(op.f('ix_loan_group_link_journal_line_id'), 'loan_group_link', ['journal_line_id'], unique=False)
    op.create_index(op.f('ix_loan_group_link_loan_group_id'), 'loan_group_link', ['loan_group_id'], unique=False)
    op.create_index(op.f('ix_loan_group_link_user_id'), 'loan_group_link', ['user_id'], unique=False)
    op.create_table('receivable_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('journal_line_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('transaction_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_dates', sa.Text(), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_line_id', sa.Integer(), nullable=True),
    sa.Column('link_kind', sa.String(length=20), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_line.id'], ),
    sa.ForeignKeyConstraint(['linked_line_id'], ['journal_line.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_line_id')
    )
    op.create_index(op.f('ix_receivable_tracker_account_id'), 'receivable_tracker', ['account_id'], unique=False)
    op.create_index(op.f('ix_receivable_tracker_journal_id'), 'receivable_tracker', ['journal_id'], unique=False)
    op.create_index(op.f('ix_receivable_tracker_user_id'), 'receivable_tracker', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivable_tracker_user_id'), table_name='receivable_tracker')
    op.drop_index(op.f('ix_receivable_tracker_journal_id'), table_name='receivable_tracker')
    op.drop_index(op.f('ix_receivable_tracker_account_id'), table_name='receivable_tracker')
    op.drop_table('receivable_tracker')
    op.drop_index(op.f('ix_loan_group_link_user_id'), table_name='loan_group_link')
    op.drop_index(op.f('ix_loan_group_link_loan_group_id'), table_name='loan_group_link')
    op.drop_index(op.f('ix_loan_group_link_journal_line_id'), table_name='loan_group_link')
    op.drop_table('loan_group_link')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_receivable_manual_entry_user_id'), table_name='receivable_manual_entry')
    op.drop_index(op.f('ix_receivable_manual_entry_account_id'), table_name='receivable_manual_entry')
    op.drop_table('receivable_manual_entry')
    op.drop_index(op.f('ix_journal_line_journal_id'), table_name='journal_line')
    op.drop_index(op.f('ix_journal_line_account_id'), table_name='journal_line')
    op.drop_table('journal_line')
    op.drop_table('account_opening_balance')
    op.drop_index(op.f('ix_account_monthly_balance_user_id'), table_name='account_monthly_balance')
    op.drop_index(op.f('ix_account_monthly_balance_account_id'), table_name='account_monthly_balance')
    op.drop_table('account_monthly_balance')
    op.drop_table('user_post')
    op.drop_index(op.f('ix_money_schedule_scenario_rows_scenario_id'), table_name='money_schedule_scenario_rows')
    op.drop_index(op.f('ix_money_schedule_scenario_rows_date'), table_name='money_schedule_scenario_rows')
    op.drop_table('money_schedule_scenario_rows')
    op.drop_table('account')
    op.drop_table('user_profile')
    op.drop_table('trial_balance_setting')
    op.drop_table('suggestion_feedback')
    op.drop_index(op.f('ix_rate_limit_bucket_user_id'), table_name='rate_limit_bucket')
    op.drop_index(op.f('ix_rate_limit_bucket_reset_at'), table_name='rate_limit_bucket')
    op.drop_index(op.f('ix_rate_limit_bucket_bucket'), table_name='rate_limit_bucket')
    op.drop_table('rate_limit_bucket')
    op.drop_index(op.f('ix_money_schedule_transactions_date'), table_name='money_schedule_transactions')
    op.drop_table('money_schedule_transactions')
    op.drop_index(op.f('ix_money_schedule_scenarios_user_id'), table_name='money_schedule_scenarios')
    op.drop_table('money_schedule_scenarios')
    op.drop_index(op.f('ix_money_schedule_rows_user_id'), table_name='money_schedule_rows')
    op.drop_index(op.f('ix_money_schedule_rows_date'), table_name='money_schedule_rows')
    op.drop_table('money_schedule_rows')
    op.drop_index(op.f('ix_money_schedule_recurring_events_user_id'), table_name='money_schedule_recurring_events')
    op.drop_index(op.f('ix_money_schedule_recurring_events_start_date'), table_name='money_schedule_recurring_events')
    op.drop_index(op.f('ix_money_schedule_recurring_events_end_date'), table_name='money_schedule_recurring_events')
    op.drop_table('money_schedule_recurring_events')
    op.drop_index(op.f('ix_money_schedule_daily_balances_user_id'), table_name='money_schedule_daily_balances')
    op.drop_index(op.f('ix_money_schedule_daily_balances_date'), table_name='money_schedule_daily_balances')
    op.drop_table('money_schedule_daily_balances')
    op.drop_index(op.f('ix_money_schedule_asset_includes_user_id'), table_name='money_schedule_asset_includes')
    op.drop_index(op.f('ix_money_schedule_asset_includes_account_id'), table_name='money_schedule_asset_includes')
    op.drop_table('money_schedule_asset_includes')
    op.drop_table('login_session')
    op.drop_index(op.f('ix_loan_group_user_id'), table_name='loan_group')
    op.drop_table('loan_group')
    op.drop_index(op.f('ix_journal_entry_user_id'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_reference'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_account_suggestion_log_user_id'), table_name='account_suggestion_log')
    op.drop_index(op.f('ix_account_suggestion_log_transaction_id'), table_name='account_suggestion_log')
    op.drop_table('account_suggestion_log')
    op.drop_table('account_suggestion_hint')
    op.drop_index(op.f('ix_account_snapshots_date'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_table('account_category')
    op.drop_table('user')
    op.drop_table('settings')
    op.drop_table('money_schedule_accounts')
    # ### end Alembic commands ###
