"""Prometheus metrics for LifeOS operational SLOs and feature rollouts."""

from __future__ import annotations

from collections.abc import Mapping

from prometheus_client import Counter, Gauge, Histogram

_INQUIRY_DOMAIN_LABELS = (
    "domain",
    "profile",
    "profile_version",
    "strategy",
    "strategy_version",
    "expert_mode",
)
_INQUIRY_ERROR_DOMAIN_LABELS = ("stage", "error_type", *_INQUIRY_DOMAIN_LABELS)

INSIGHT_LATENCY_SECONDS = Histogram(
    "lifeos_insight_latency_seconds",
    "Insight generation latency in seconds",
    buckets=(0.05, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0),
)

PROJECTION_CORRECTNESS_TOTAL = Counter(
    "lifeos_projection_correctness_total",
    "Total read-only projection checks",
)

PROJECTION_CORRECTNESS_ERRORS_TOTAL = Counter(
    "lifeos_projection_correctness_errors_total",
    "Read-only projection correctness errors",
)

REPLAY_DETERMINISM_FAILURES_TOTAL = Counter(
    "lifeos_replay_determinism_failures_total",
    "Replay determinism failures",
)

CONTRACT_VIOLATIONS_TOTAL = Counter(
    "lifeos_contract_violations_total",
    "API contract violations",
)

READ_CACHE_HITS_TOTAL = Counter(
    "lifeos_read_cache_hits_total",
    "Read-through cache hits",
    ["scope"],
)

READ_CACHE_MISSES_TOTAL = Counter(
    "lifeos_read_cache_misses_total",
    "Read-through cache misses",
    ["scope"],
)

HTTP_REQUEST_LATENCY_SECONDS = Histogram(
    "lifeos_http_request_latency_seconds",
    "HTTP request latency in seconds",
    ["method", "route", "status_code"],
    buckets=(0.05, 0.1, 0.2, 0.35, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0),
)

EVENT_DISPATCH_LATENCY_SECONDS = Histogram(
    "lifeos_event_dispatch_latency_seconds",
    "In-process event dispatch latency in seconds",
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0),
)

INQUIRY_CREATED_TOTAL = Counter(
    "lifeos_inquiry_created_total",
    "Total focused inquiries created",
)

INQUIRY_GENERATED_TOTAL = Counter(
    "lifeos_inquiry_generated_total",
    "Total focused inquiry briefs generated",
)

INQUIRY_GENERATED_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_generated_by_domain_total",
    "Total focused inquiry briefs generated by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_VIEWED_TOTAL = Counter(
    "lifeos_inquiry_viewed_total",
    "Total focused inquiry brief views",
)

INQUIRY_REFINED_TOTAL = Counter(
    "lifeos_inquiry_refined_total",
    "Total focused inquiry refinements",
)

INQUIRY_REFINED_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_refined_by_domain_total",
    "Total focused inquiry refinements by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_GENERATION_LATENCY_SECONDS = Histogram(
    "lifeos_inquiry_generation_latency_seconds",
    "Focused inquiry generation latency in seconds",
    buckets=(0.05, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0),
)

INQUIRY_GENERATION_LATENCY_SECONDS_BY_DOMAIN = Histogram(
    "lifeos_inquiry_generation_latency_seconds_by_domain",
    "Focused inquiry generation latency in seconds by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
    buckets=(0.05, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0),
)

INQUIRY_ERRORS_TOTAL = Counter(
    "lifeos_inquiry_errors_total",
    "Total focused inquiry pipeline errors",
    ["stage", "error_type"],
)

INQUIRY_ERRORS_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_errors_by_domain_total",
    "Total focused inquiry pipeline errors by domain strategy profile",
    _INQUIRY_ERROR_DOMAIN_LABELS,
)

INQUIRY_EMPTY_BRIEF_TOTAL = Counter(
    "lifeos_inquiry_empty_brief_total",
    "Total focused inquiry briefs with zero evidence coverage",
)

INQUIRY_EMPTY_BRIEF_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_empty_brief_by_domain_total",
    "Total focused inquiry briefs with zero evidence coverage by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_FINDINGS_TOTAL = Counter(
    "lifeos_inquiry_findings_total",
    "Total focused inquiry findings generated",
)

INQUIRY_FINDINGS_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_findings_by_domain_total",
    "Total focused inquiry findings generated by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_FINDINGS_WITH_EVIDENCE_TOTAL = Counter(
    "lifeos_inquiry_findings_with_evidence_total",
    "Total focused inquiry findings that include at least one evidence reference",
)

INQUIRY_FINDINGS_WITH_EVIDENCE_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_findings_with_evidence_by_domain_total",
    "Total focused inquiry findings with evidence by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_LOW_COVERAGE_TOTAL = Counter(
    "lifeos_inquiry_low_coverage_total",
    "Total focused inquiry briefs with low evidence coverage",
)

INQUIRY_LOW_COVERAGE_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_low_coverage_by_domain_total",
    "Total focused inquiry low-coverage briefs by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_REFINE_AFTER_LOW_QUALITY_TOTAL = Counter(
    "lifeos_inquiry_refine_after_low_quality_total",
    "Total refine operations executed after a low-quality brief",
)

INQUIRY_REFINE_AFTER_LOW_QUALITY_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_refine_after_low_quality_by_domain_total",
    "Total refine-after-low-quality operations by domain strategy profile",
    _INQUIRY_DOMAIN_LABELS,
)

INQUIRY_QUALITY_STATE_TOTAL = Counter(
    "lifeos_inquiry_quality_state_total",
    "Focused inquiry quality state distribution",
    ["state"],
)

INQUIRY_QUALITY_STATE_BY_DOMAIN_TOTAL = Counter(
    "lifeos_inquiry_quality_state_by_domain_total",
    "Focused inquiry quality state distribution by domain strategy profile",
    (*_INQUIRY_DOMAIN_LABELS, "state"),
)

INQUIRY_ERROR_RATE = Gauge(
    "lifeos_inquiry_error_rate",
    "Focused inquiry runtime error ratio",
)

INQUIRY_EMPTY_BRIEF_RATE = Gauge(
    "lifeos_inquiry_empty_brief_rate",
    "Focused inquiry empty-brief ratio",
)

INQUIRY_EVIDENCE_COVERAGE_RATIO = Gauge(
    "lifeos_inquiry_evidence_coverage_ratio",
    "Focused inquiry findings with evidence ratio",
)

INQUIRY_LOW_COVERAGE_RATE = Gauge(
    "lifeos_inquiry_low_coverage_rate",
    "Focused inquiry low-coverage ratio",
)

INQUIRY_REFINE_AFTER_LOW_QUALITY_RATE = Gauge(
    "lifeos_inquiry_refine_after_low_quality_rate",
    "Focused inquiry refine-after-low-quality ratio",
)

PHASE6_INQUIRY_MIGRATION_MISMATCH = Gauge(
    "lifeos_phase6_inquiry_migration_mismatch",
    "Focused Inquiry migration mismatch state (1=mismatch, 0=applied)",
    ["expected_head"],
)

_LOW_COVERAGE_THRESHOLD = 0.8
_QUALITY_STATES = ("sufficient", "low_coverage", "empty", "needs_refine", "unknown")


def _domain_metric_labels(
    *,
    domain: str | None,
    profile: str | None,
    profile_version: str | None,
    strategy: str | None,
    strategy_version: str | None,
    expert_mode: bool | str | None,
) -> dict[str, str]:
    def _text(value: object | None, *, default: str = "unknown") -> str:
        rendered = str(value or "").strip()
        return rendered or default

    if isinstance(expert_mode, str):
        expert = expert_mode.strip().lower() in {"1", "true", "yes", "on"}
    else:
        expert = bool(expert_mode)
    return {
        "domain": _text(domain),
        "profile": _text(profile),
        "profile_version": _text(profile_version),
        "strategy": _text(strategy),
        "strategy_version": _text(strategy_version),
        "expert_mode": "true" if expert else "false",
    }


# Pre-register a default label set so histograms appear even without traffic.
HTTP_REQUEST_LATENCY_SECONDS.labels(method="GET", route="unknown", status_code="200")
EVENT_DISPATCH_LATENCY_SECONDS.observe(0)
INQUIRY_ERRORS_TOTAL.labels(stage="create", error_type="validation_error").inc(0)
INQUIRY_ERRORS_TOTAL.labels(stage="create", error_type="internal_error").inc(0)
INQUIRY_ERRORS_TOTAL.labels(stage="refine", error_type="validation_error").inc(0)
INQUIRY_ERRORS_TOTAL.labels(stage="refine", error_type="internal_error").inc(0)
INQUIRY_ERRORS_TOTAL.labels(stage="list", error_type="validation_error").inc(0)
INQUIRY_ERRORS_TOTAL.labels(stage="detail", error_type="not_found").inc(0)
_UNKNOWN_DOMAIN_LABELS = _domain_metric_labels(
    domain="unknown",
    profile="unknown",
    profile_version="unknown",
    strategy="unknown",
    strategy_version="unknown",
    expert_mode=False,
)
INQUIRY_GENERATED_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_REFINED_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_GENERATION_LATENCY_SECONDS_BY_DOMAIN.labels(**_UNKNOWN_DOMAIN_LABELS)
INQUIRY_ERRORS_BY_DOMAIN_TOTAL.labels(stage="unknown", error_type="unknown", **_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_EMPTY_BRIEF_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_FINDINGS_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_FINDINGS_WITH_EVIDENCE_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_LOW_COVERAGE_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_REFINE_AFTER_LOW_QUALITY_BY_DOMAIN_TOTAL.labels(**_UNKNOWN_DOMAIN_LABELS).inc(0)
for _state in _QUALITY_STATES:
    INQUIRY_QUALITY_STATE_TOTAL.labels(state=_state).inc(0)
    INQUIRY_QUALITY_STATE_BY_DOMAIN_TOTAL.labels(state=_state, **_UNKNOWN_DOMAIN_LABELS).inc(0)
INQUIRY_ERROR_RATE.set(0.0)
INQUIRY_EMPTY_BRIEF_RATE.set(0.0)
INQUIRY_EVIDENCE_COVERAGE_RATIO.set(1.0)
INQUIRY_LOW_COVERAGE_RATE.set(0.0)
INQUIRY_REFINE_AFTER_LOW_QUALITY_RATE.set(0.0)

_inquiry_generated_count = 0
_inquiry_error_count = 0
_inquiry_empty_count = 0
_inquiry_findings_count = 0
_inquiry_findings_with_evidence_count = 0
_inquiry_low_coverage_count = 0
_inquiry_refined_count = 0
_inquiry_refine_after_low_quality_count = 0


def record_insight_latency_ms(latency_ms: float) -> None:
    """Record insight latency in milliseconds."""
    if latency_ms is None:
        return
    INSIGHT_LATENCY_SECONDS.observe(max(0.0, latency_ms / 1000.0))


def record_projection_check() -> None:
    """Record a read-only projection evaluation."""
    PROJECTION_CORRECTNESS_TOTAL.inc()


def record_projection_error() -> None:
    """Record a projection correctness failure."""
    PROJECTION_CORRECTNESS_ERRORS_TOTAL.inc()


def record_replay_determinism_failure() -> None:
    """Record a replay determinism failure."""
    REPLAY_DETERMINISM_FAILURES_TOTAL.inc()


def record_contract_violation() -> None:
    """Record an API contract violation."""
    CONTRACT_VIOLATIONS_TOTAL.inc()


def record_read_cache_hit(scope: str) -> None:
    """Record a read cache hit by scope."""
    READ_CACHE_HITS_TOTAL.labels(scope=scope).inc()


def record_read_cache_miss(scope: str) -> None:
    """Record a read cache miss by scope."""
    READ_CACHE_MISSES_TOTAL.labels(scope=scope).inc()


def record_http_request_latency_seconds(
    duration_seconds: float,
    method: str,
    route: str,
    status_code: str,
) -> None:
    """Record HTTP request latency in seconds."""
    if duration_seconds is None:
        return
    HTTP_REQUEST_LATENCY_SECONDS.labels(
        method=method or "unknown",
        route=route or "unknown",
        status_code=status_code or "0",
    ).observe(max(0.0, duration_seconds))


def record_event_dispatch_latency_seconds(duration_seconds: float) -> None:
    """Record in-process event dispatch latency in seconds."""
    if duration_seconds is None:
        return
    EVENT_DISPATCH_LATENCY_SECONDS.observe(max(0.0, duration_seconds))


def _safe_ratio(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return max(0.0, float(numerator) / float(denominator))


def _coerce_quality_metadata(
    quality_metadata: Mapping[str, object] | None,
    findings_total: int,
    findings_with_evidence: int,
) -> dict[str, object]:
    if isinstance(quality_metadata, Mapping):
        return dict(quality_metadata)
    coverage = _safe_ratio(findings_with_evidence, findings_total)
    return {
        "findings_total": findings_total,
        "findings_with_evidence": findings_with_evidence,
        "evidence_coverage_ratio": coverage,
        "structure_gaps": [],
        "sparse_domains": [],
    }


def _is_low_quality_metadata(quality_metadata: Mapping[str, object] | None) -> bool:
    if not isinstance(quality_metadata, Mapping):
        return False
    findings_total = int(quality_metadata.get("findings_total") or 0)
    coverage = float(quality_metadata.get("evidence_coverage_ratio") or 0.0)
    structure_gaps = list(quality_metadata.get("structure_gaps") or [])
    sparse_domains = list(quality_metadata.get("sparse_domains") or [])
    if findings_total == 0:
        return True
    return coverage < _LOW_COVERAGE_THRESHOLD or bool(structure_gaps) or bool(sparse_domains)


def _quality_state(quality_metadata: Mapping[str, object] | None) -> str:
    if not isinstance(quality_metadata, Mapping):
        return "unknown"
    findings_total = int(quality_metadata.get("findings_total") or 0)
    coverage = float(quality_metadata.get("evidence_coverage_ratio") or 0.0)
    structure_gaps = list(quality_metadata.get("structure_gaps") or [])
    sparse_domains = list(quality_metadata.get("sparse_domains") or [])
    if findings_total == 0:
        return "empty"
    if coverage < _LOW_COVERAGE_THRESHOLD:
        return "low_coverage"
    if bool(structure_gaps) or bool(sparse_domains):
        return "needs_refine"
    return "sufficient"


def record_inquiry_created() -> None:
    """Record successful focused inquiry creation."""
    INQUIRY_CREATED_TOTAL.inc()


def record_inquiry_generated(
    *,
    latency_seconds: float | None,
    is_empty: bool,
    findings_total: int,
    findings_with_evidence: int,
    quality_metadata: Mapping[str, object] | None = None,
    domain: str | None = None,
    profile: str | None = None,
    profile_version: str | None = None,
    strategy: str | None = None,
    strategy_version: str | None = None,
    expert_mode: bool | str | None = None,
) -> None:
    """Record focused inquiry brief generation and coverage stats."""
    global _inquiry_generated_count
    global _inquiry_empty_count
    global _inquiry_findings_count
    global _inquiry_findings_with_evidence_count
    global _inquiry_low_coverage_count

    domain_labels = _domain_metric_labels(
        domain=domain,
        profile=profile,
        profile_version=profile_version,
        strategy=strategy,
        strategy_version=strategy_version,
        expert_mode=expert_mode,
    )
    INQUIRY_GENERATED_TOTAL.inc()
    INQUIRY_GENERATED_BY_DOMAIN_TOTAL.labels(**domain_labels).inc()
    _inquiry_generated_count += 1

    if latency_seconds is not None:
        INQUIRY_GENERATION_LATENCY_SECONDS.observe(max(0.0, latency_seconds))
        INQUIRY_GENERATION_LATENCY_SECONDS_BY_DOMAIN.labels(**domain_labels).observe(max(0.0, latency_seconds))

    if is_empty:
        INQUIRY_EMPTY_BRIEF_TOTAL.inc()
        INQUIRY_EMPTY_BRIEF_BY_DOMAIN_TOTAL.labels(**domain_labels).inc()
        _inquiry_empty_count += 1

    findings_total = max(0, int(findings_total))
    findings_with_evidence = max(0, min(findings_total, int(findings_with_evidence)))
    if findings_total:
        INQUIRY_FINDINGS_TOTAL.inc(findings_total)
        INQUIRY_FINDINGS_WITH_EVIDENCE_TOTAL.inc(findings_with_evidence)
        INQUIRY_FINDINGS_BY_DOMAIN_TOTAL.labels(**domain_labels).inc(findings_total)
        INQUIRY_FINDINGS_WITH_EVIDENCE_BY_DOMAIN_TOTAL.labels(**domain_labels).inc(findings_with_evidence)
        _inquiry_findings_count += findings_total
        _inquiry_findings_with_evidence_count += findings_with_evidence

    quality = _coerce_quality_metadata(quality_metadata, findings_total, findings_with_evidence)
    state = _quality_state(quality)
    INQUIRY_QUALITY_STATE_TOTAL.labels(state=state).inc()
    INQUIRY_QUALITY_STATE_BY_DOMAIN_TOTAL.labels(state=state, **domain_labels).inc()
    if state == "low_coverage":
        INQUIRY_LOW_COVERAGE_TOTAL.inc()
        INQUIRY_LOW_COVERAGE_BY_DOMAIN_TOTAL.labels(**domain_labels).inc()
        _inquiry_low_coverage_count += 1

    INQUIRY_EMPTY_BRIEF_RATE.set(_safe_ratio(_inquiry_empty_count, _inquiry_generated_count))
    INQUIRY_EVIDENCE_COVERAGE_RATIO.set(_safe_ratio(_inquiry_findings_with_evidence_count, _inquiry_findings_count))
    INQUIRY_LOW_COVERAGE_RATE.set(_safe_ratio(_inquiry_low_coverage_count, _inquiry_generated_count))
    INQUIRY_ERROR_RATE.set(_safe_ratio(_inquiry_error_count, _inquiry_generated_count + _inquiry_error_count))


def record_inquiry_viewed() -> None:
    """Record focused inquiry brief view."""
    INQUIRY_VIEWED_TOTAL.inc()


def record_inquiry_refined(
    *,
    domain: str | None = None,
    profile: str | None = None,
    profile_version: str | None = None,
    strategy: str | None = None,
    strategy_version: str | None = None,
    expert_mode: bool | str | None = None,
) -> None:
    """Record focused inquiry refinement."""
    global _inquiry_refined_count
    domain_labels = _domain_metric_labels(
        domain=domain,
        profile=profile,
        profile_version=profile_version,
        strategy=strategy,
        strategy_version=strategy_version,
        expert_mode=expert_mode,
    )
    INQUIRY_REFINED_TOTAL.inc()
    INQUIRY_REFINED_BY_DOMAIN_TOTAL.labels(**domain_labels).inc()
    _inquiry_refined_count += 1
    INQUIRY_REFINE_AFTER_LOW_QUALITY_RATE.set(
        _safe_ratio(_inquiry_refine_after_low_quality_count, _inquiry_refined_count)
    )


def record_inquiry_refine_after_low_quality(
    previous_quality_metadata: Mapping[str, object] | None,
    *,
    domain: str | None = None,
    profile: str | None = None,
    profile_version: str | None = None,
    strategy: str | None = None,
    strategy_version: str | None = None,
    expert_mode: bool | str | None = None,
) -> None:
    """Record refine operations that occur after a low-quality brief."""
    global _inquiry_refine_after_low_quality_count
    if not _is_low_quality_metadata(previous_quality_metadata):
        return
    domain_labels = _domain_metric_labels(
        domain=domain,
        profile=profile,
        profile_version=profile_version,
        strategy=strategy,
        strategy_version=strategy_version,
        expert_mode=expert_mode,
    )
    INQUIRY_REFINE_AFTER_LOW_QUALITY_TOTAL.inc()
    INQUIRY_REFINE_AFTER_LOW_QUALITY_BY_DOMAIN_TOTAL.labels(**domain_labels).inc()
    _inquiry_refine_after_low_quality_count += 1
    INQUIRY_REFINE_AFTER_LOW_QUALITY_RATE.set(
        _safe_ratio(_inquiry_refine_after_low_quality_count, _inquiry_refined_count)
    )


def record_inquiry_error(
    stage: str,
    error_type: str,
    *,
    domain: str | None = None,
    profile: str | None = None,
    profile_version: str | None = None,
    strategy: str | None = None,
    strategy_version: str | None = None,
    expert_mode: bool | str | None = None,
) -> None:
    """Record focused inquiry pipeline errors."""
    global _inquiry_error_count
    domain_labels = _domain_metric_labels(
        domain=domain,
        profile=profile,
        profile_version=profile_version,
        strategy=strategy,
        strategy_version=strategy_version,
        expert_mode=expert_mode,
    )
    INQUIRY_ERRORS_TOTAL.labels(stage=stage or "unknown", error_type=error_type or "unknown").inc()
    INQUIRY_ERRORS_BY_DOMAIN_TOTAL.labels(
        stage=stage or "unknown",
        error_type=error_type or "unknown",
        **domain_labels,
    ).inc()
    _inquiry_error_count += 1
    INQUIRY_ERROR_RATE.set(_safe_ratio(_inquiry_error_count, _inquiry_generated_count + _inquiry_error_count))


def set_phase6_inquiry_migration_mismatch(expected_head: str, mismatch: bool) -> None:
    """Expose Focused Inquiry migration head state for deployment health."""
    PHASE6_INQUIRY_MIGRATION_MISMATCH.labels(expected_head=expected_head or "unknown").set(1 if mismatch else 0)
