global:
  resolve_timeout: 5m

route:
  receiver: 'null'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: 'null'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'alertname']

  - source_match:
      alertname: 'Maintenance'
    target_match_re:
      alertname: '.*'
    equal: ['service']
