"""DSD field mappings for Phase 3b contract enforcement."""

from __future__ import annotations

DSD_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    "finance:journal": {
        "Response.ok": "Response ok",
        "Response.entries": "Response entries",
        "Response.total_entries": "Response total entries",
        "Response.entry": "Response entry",
        "JournalEntryItem.id": "Entry id",
        "JournalEntryItem.entry_number": "Entry number",
        "JournalEntryItem.description": "Entry description",
        "JournalEntryItem.posted_at": "Occurred date",
        "JournalEntryItem.lines": "Line count",
        "JournalEntryItem.debit_total": "Debit total",
        "JournalEntryItem.credit_total": "Credit total",
        "JournalEntryDetail.id": "Entry id",
        "JournalEntryDetail.description": "Entry description",
        "JournalEntryDetail.posted_at": "Occurred date",
        "JournalEntryDetail.debit_total": "Debit total",
        "JournalEntryDetail.credit_total": "Credit total",
        "JournalEntryDetail.lines": "Journal lines",
        "JournalLineItem.id": "Journal line id",
        "JournalLineItem.account_id": "Journal line account id",
        "JournalLineItem.account_name": "Journal line account name",
        "JournalLineItem.debit": "Journal line debit",
        "JournalLineItem.credit": "Journal line credit",
        "JournalLineItem.memo": "Journal line memo",
    },
    "finance:trial_balance": {
        "Response.ok": "Response ok",
        "Response.accounts": "Response accounts",
        "Response.categories": "Response categories",
        "Response.totals": "Response totals",
        "Response.months": "Response months",
        "TrialBalanceAccountItem.account_id": "Account id",
        "TrialBalanceAccountItem.account_name": "Account name",
        "TrialBalanceAccountItem.account_code": "Account code",
        "TrialBalanceAccountItem.base_type": "Account base type",
        "TrialBalanceAccountItem.category_id": "Category id",
        "TrialBalanceAccountItem.category_name": "Category name",
        "TrialBalanceAccountItem.normal_balance": "Normal balance",
        "TrialBalanceAccountItem.debit": "Debit total",
        "TrialBalanceAccountItem.credit": "Credit total",
        "TrialBalanceAccountItem.net": "Net balance",
        "TrialBalanceCategoryItem.base_type": "Account base type",
        "TrialBalanceCategoryItem.category_id": "Category id",
        "TrialBalanceCategoryItem.category_name": "Category name",
        "TrialBalanceCategoryItem.normal_balance": "Normal balance",
        "TrialBalanceCategoryItem.debit": "Debit total",
        "TrialBalanceCategoryItem.credit": "Credit total",
        "TrialBalanceCategoryItem.net": "Net balance",
    },
    "finance:receivables": {
        "Response.ok": "Response ok",
        "Response.items": "Response items",
        "Response.tracker": "Response tracker",
        "Response.page": "Response page",
        "Response.pages": "Response pages",
        "Response.total": "Response total",
        "ReceivableItem.id": "Receivable id",
        "ReceivableItem.counterparty": "Counterparty",
        "ReceivableItem.principal": "Principal",
        "ReceivableItem.start_date": "Start date",
        "ReceivableItem.due_date": "Due date",
        "ReceivableItem.interest_rate": "Interest rate",
        "ReceivableEntryItem.id": "Receivable entry id",
        "ReceivableEntryItem.tracker_id": "Receivable tracker id",
        "ReceivableEntryItem.entry_date": "Entry date",
        "ReceivableEntryItem.amount": "Entry amount",
        "ReceivableEntryItem.memo": "Entry memo",
    },
    "finance:forecast": {
        "Response.ok": "Response ok",
        "Response.forecast": "Response forecast",
        "ForecastItem.date": "Forecast date",
        "ForecastItem.projected_balance": "Projected balance",
    },
    "insights:inquiry": {
        "Response.ok": "Response ok",
        "Response.deduped": "Response deduped",
        "Response.inquiry_id": "Response inquiry id",
        "Response.version_id": "Response version id",
        "Response.version_number": "Response version number",
        "Response.inquiry": "Response inquiry",
        "Response.latest_brief": "Response latest brief",
        "Response.items": "Response items",
        "Response.total": "Response total",
        "Response.limit": "Response limit",
        "Response.offset": "Response offset",
        "Response.brief": "Response brief",
        "InquiryItem.id": "Inquiry id",
        "InquiryItem.question": "Question",
        "InquiryItem.lens": "Lens",
        "InquiryItem.domain": "Primary domain",
        "InquiryItem.domains": "Selected domains",
        "InquiryItem.timeframe": "Timeframe object",
        "InquiryItem.as_of_ts": "As of timestamp",
        "InquiryItem.context_non_evidence": "Context block",
        "InquiryItem.created_at": "Created timestamp",
        "InquiryItem.updated_at": "Updated timestamp",
        "InquiryItem.last_version_number": "Last version number",
        "InquiryItem.latest_brief": "Latest brief object",
        "InquiryItem.versions": "Version history list",
        "InquiryVersionItem.id": "Brief version id",
        "InquiryVersionItem.version_number": "Brief version number",
        "InquiryVersionItem.parent_version_id": "Parent version id",
        "InquiryVersionItem.created_at": "Brief created timestamp",
        "InquiryVersionItem.brief_hash": "Brief hash",
        "InquiryVersionItem.as_of_ts": "Brief as of timestamp",
        "InquiryVersionItem.brief": "Brief payload",
        "InquiryBriefItem.summary": "Brief summary",
        "InquiryBriefItem.findings": "Brief findings",
        "InquiryBriefItem.direct_answer": "Brief direct answer",
        "InquiryBriefItem.answerability": "Brief answerability block",
        "InquiryBriefItem.context_non_evidence": "Brief context non evidence",
        "InquiryBriefItem.uncertainty_note": "Brief uncertainty note",
        "InquiryBriefItem.limits": "Brief limits",
        "InquiryBriefItem.limitation_items": "Brief limitation items",
        "InquiryBriefItem.refine_guidance": "Brief refine guidance",
        "InquiryBriefItem.bounded_patterns": "Brief bounded patterns",
        "InquiryBriefItem.productization_metadata": "Brief productization metadata",
        "InquiryBriefItem.question": "Question",
        "InquiryBriefItem.lens": "Lens",
        "InquiryBriefItem.domains": "Selected domains",
        "InquiryBriefItem.timeframe": "Timeframe object",
        "InquiryBriefItem.as_of_ts": "As of timestamp",
        "InquiryBriefItem.generated_at": "Brief generated timestamp",
        "InquiryBriefItem.brief_profile": "Brief profile metadata",
        "InquiryBriefItem.timeline_metadata": "Brief timeline metadata",
        "InquiryBriefItem.humanized_brief": "Brief humanized rendering",
        "InquiryBriefItem.quality_metadata": "Brief quality metadata",
        "InquiryFindingItem.finding_id": "Canonical finding id",
        "InquiryFindingItem.claim": "Finding claim",
        "InquiryFindingItem.finding_category": "Finding category",
        "InquiryFindingItem.evidence_refs": "Finding evidence refs",
        "InquiryFindingItem.relevance_rank": "Finding relevance rank",
        "InquiryFindingItem.relevance_reason": "Finding relevance reason",
        "InquiryFindingItem.confidence_label": "Finding confidence label",
        "InquiryFindingItem.uncertainty_note": "Finding uncertainty note",
        "InquiryFindingItem.source_domains": "Finding source domains",
        "InquiryFindingItem.timeline_context": "Finding timeline context",
        "InquiryLimitationItem.limitation_id": "Canonical limitation id",
        "InquiryLimitationItem.text": "Limitation text",
        "InquiryEvidenceRef.source_kind": "Evidence source kind",
        "InquiryEvidenceRef.source_id": "Evidence source id",
        "InquiryEvidenceRef.source_ref": "Evidence source ref",
        "InquiryEvidenceRef.event_type": "Evidence event type",
        "InquiryEvidenceRef.domain": "Evidence domain",
        "InquiryEvidenceRef.created_at": "Evidence created at",
        "InquiryEvidenceRef.event_count": "Evidence event count",
        "InquiryEvidenceRef.insight_count": "Evidence insight count",
        "InquiryContextBlock.label": "Context label",
        "InquiryContextBlock.text": "Context block",
        "InquiryContextBlock.note": "Context note",
        "InquiryBriefProfile.profile": "Brief profile key",
        "InquiryBriefProfile.profile_version": "Brief profile version",
        "InquiryBriefProfile.strategy": "Brief strategy key",
        "InquiryBriefProfile.strategy_version": "Brief strategy version",
        "InquiryBriefProfile.domain": "Brief profile domain",
        "InquiryBriefProfile.expert_mode": "Brief expert mode",
        "InquiryBriefProfile.finding_categories": "Brief finding categories",
        "InquiryTimelineContext.claim_type": "Timeline claim type",
        "InquiryTimelineContext.active_window_label": "Timeline active window label",
        "InquiryTimelineContext.comparison_label": "Timeline comparison label",
        "InquiryTimelineContext.window_spec_token": "Timeline window spec token",
        "InquiryTimelineContext.baseline_policy_token": "Timeline baseline policy token",
        "InquiryTimelineContext.coverage_status": "Timeline coverage status",
        "InquiryTimelineMetadata.timeline_profile_id": "Timeline profile id",
        "InquiryTimelineMetadata.timeline_profile_version": "Timeline profile version",
        "InquiryTimelineMetadata.timeline_engine_version": "Timeline engine version",
        "InquiryTimelineMetadata.window_spec_token": "Timeline metadata window spec token",
        "InquiryTimelineMetadata.active_window_token": "Timeline active window token",
        "InquiryTimelineMetadata.comparison_window_token": "Timeline comparison window token",
        "InquiryTimelineMetadata.baseline_policy_token": "Timeline metadata baseline policy token",
        "InquiryTimelineMetadata.timezone_token": "Timeline timezone token",
        "InquiryTimelineMetadata.as_of_ts": "Timeline metadata as of timestamp",
        "InquiryTimelineMetadata.evidence_manifest_hash": "Timeline evidence manifest hash",
        "InquiryTimelineMetadata.timeline_summary_hash": "Timeline summary hash",
        "InquiryTimelineMetadata.comparison_coverage": "Timeline comparison coverage",
        "InquiryTimelineMetadata.finding_count": "Timeline finding count",
        "InquiryTimelineMetadata.insufficiency_count": "Timeline insufficiency count",
        "InquiryHumanizedMetadata.canonical_brief_hash": "Humanized canonical brief hash",
        "InquiryHumanizedMetadata.humanization_version": "Humanization version",
        "InquiryHumanizedMetadata.humanized_brief_hash": "Humanized brief hash",
        "InquiryHumanizedMetadata.technical_view_available": "Technical view available",
        "InquiryHumanizedAnswer.text": "Humanized answer text",
        "InquiryHumanizedAnswer.source_finding_ids": "Humanized answer source finding ids",
        "InquiryHumanizedAnswer.source_limitation_ids": "Humanized answer source limitation ids",
        "InquiryHumanizedBlock.block_id": "Humanized block id",
        "InquiryHumanizedBlock.text": "Humanized block text",
        "InquiryHumanizedBlock.source_finding_ids": "Humanized block source finding ids",
        "InquiryHumanizedBlock.source_limitation_ids": "Humanized block source limitation ids",
        "InquiryHumanizedBlock.evidence_refs": "Humanized block evidence refs",
        "InquiryHumanizedBlock.confidence_label": "Humanized block confidence label",
        "InquiryHumanizedSection.section_id": "Humanized section id",
        "InquiryHumanizedSection.title": "Humanized section title",
        "InquiryHumanizedSection.blocks": "Humanized section blocks",
        "InquiryHumanizedBrief.metadata": "Humanized brief metadata",
        "InquiryHumanizedBrief.answer": "Humanized brief answer",
        "InquiryHumanizedBrief.sections": "Humanized brief sections",
        "InquiryTimelineCoverage.prior_window_available": "Timeline prior window availability",
        "InquiryTimelineCoverage.baseline_windows_available": "Timeline baseline windows available",
        "InquiryTimelineCoverage.baseline_windows_required": "Timeline baseline windows required",
        "InquiryTimelineCoverage.recurrence_windows_available": "Timeline recurrence windows available",
        "InquiryTimelineCoverage.trend_windows_available": "Timeline trend windows available",
        "InquiryQualityMetadata.findings_total": "Quality findings total",
        "InquiryQualityMetadata.findings_with_evidence": "Quality findings with evidence",
        "InquiryQualityMetadata.evidence_coverage_ratio": "Quality evidence coverage ratio",
        "InquiryQualityMetadata.structure_gaps": "Quality structure gaps",
        "InquiryQualityMetadata.sparse_domains": "Quality sparse domains",
        "InquiryQualityMetadata.refine_guidance": "Quality refine guidance",
        "InquiryDirectAnswer.text": "Direct answer text",
        "InquiryDirectAnswer.supporting_claims": "Direct answer supporting claims",
        "InquiryDirectAnswer.note": "Direct answer note",
        "InquiryAnswerability.classification": "Answerability classification",
        "InquiryAnswerability.reason": "Answerability reason",
        "InquiryAnswerability.evidence_coverage_ratio": "Answerability evidence coverage ratio",
        "InquiryAnswerability.supporting_finding_count": "Answerability supporting finding count",
        "InquiryBoundedPattern.pattern_category": "Bounded pattern category",
        "InquiryBoundedPattern.finding_count": "Bounded pattern finding count",
        "InquiryBoundedPattern.note": "Bounded pattern note",
        "InquiryProductizationMetadata.version": "Productization version",
        "InquiryProductizationMetadata.limitation_count_before": "Limitations before dedupe",
        "InquiryProductizationMetadata.limitation_count_after": "Limitations after dedupe",
        "InquiryProductizationMetadata.limitation_redundancy_removed": "Removed duplicate limitations",
        "InquiryProductizationMetadata.direct_answer_present": "Direct answer presence",
    },
}


__all__ = ["DSD_FIELD_MAPPINGS"]
