"""DSD field mappings for Phase 3b contract enforcement."""

from __future__ import annotations

DSD_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    "finance:journal": {
        "Response.ok": "Response ok",
        "Response.entries": "Response entries",
        "Response.total_entries": "Response total entries",
        "Response.entry": "Response entry",
        "JournalEntryItem.id": "Entry id",
        "JournalEntryItem.entry_number": "Entry number",
        "JournalEntryItem.description": "Entry description",
        "JournalEntryItem.posted_at": "Occurred date",
        "JournalEntryItem.lines": "Line count",
        "JournalEntryItem.debit_total": "Debit total",
        "JournalEntryItem.credit_total": "Credit total",
        "JournalEntryDetail.id": "Entry id",
        "JournalEntryDetail.description": "Entry description",
        "JournalEntryDetail.posted_at": "Occurred date",
        "JournalEntryDetail.debit_total": "Debit total",
        "JournalEntryDetail.credit_total": "Credit total",
        "JournalEntryDetail.lines": "Journal lines",
        "JournalLineItem.id": "Journal line id",
        "JournalLineItem.account_id": "Journal line account id",
        "JournalLineItem.account_name": "Journal line account name",
        "JournalLineItem.debit": "Journal line debit",
        "JournalLineItem.credit": "Journal line credit",
        "JournalLineItem.memo": "Journal line memo",
    },
    "finance:trial_balance": {
        "Response.ok": "Response ok",
        "Response.accounts": "Response accounts",
        "Response.categories": "Response categories",
        "Response.totals": "Response totals",
        "Response.months": "Response months",
        "TrialBalanceAccountItem.account_id": "Account id",
        "TrialBalanceAccountItem.account_name": "Account name",
        "TrialBalanceAccountItem.account_code": "Account code",
        "TrialBalanceAccountItem.base_type": "Account base type",
        "TrialBalanceAccountItem.category_id": "Category id",
        "TrialBalanceAccountItem.category_name": "Category name",
        "TrialBalanceAccountItem.normal_balance": "Normal balance",
        "TrialBalanceAccountItem.debit": "Debit total",
        "TrialBalanceAccountItem.credit": "Credit total",
        "TrialBalanceAccountItem.net": "Net balance",
        "TrialBalanceCategoryItem.base_type": "Account base type",
        "TrialBalanceCategoryItem.category_id": "Category id",
        "TrialBalanceCategoryItem.category_name": "Category name",
        "TrialBalanceCategoryItem.normal_balance": "Normal balance",
        "TrialBalanceCategoryItem.debit": "Debit total",
        "TrialBalanceCategoryItem.credit": "Credit total",
        "TrialBalanceCategoryItem.net": "Net balance",
    },
    "finance:receivables": {
        "Response.ok": "Response ok",
        "Response.items": "Response items",
        "Response.tracker": "Response tracker",
        "Response.page": "Response page",
        "Response.pages": "Response pages",
        "Response.total": "Response total",
        "ReceivableItem.id": "Receivable id",
        "ReceivableItem.counterparty": "Counterparty",
        "ReceivableItem.principal": "Principal",
        "ReceivableItem.start_date": "Start date",
        "ReceivableItem.due_date": "Due date",
        "ReceivableItem.interest_rate": "Interest rate",
        "ReceivableEntryItem.id": "Receivable entry id",
        "ReceivableEntryItem.tracker_id": "Receivable tracker id",
        "ReceivableEntryItem.entry_date": "Entry date",
        "ReceivableEntryItem.amount": "Entry amount",
        "ReceivableEntryItem.memo": "Entry memo",
    },
    "finance:forecast": {
        "Response.ok": "Response ok",
        "Response.forecast": "Response forecast",
        "ForecastItem.date": "Forecast date",
        "ForecastItem.projected_balance": "Projected balance",
    },
}


__all__ = ["DSD_FIELD_MAPPINGS"]
